auto:      true
pygments:  true
permalink: pretty
paginate:  5

exclude:
    - README.md
    - README.txt

title:   Godin
comment: Man from nowhere
feed:    http://feeds.feedburner.com/godin/

author:
    name: Evgeny Mandrikov

# Google Analytics
ga:
    id: UA-6691139-1

nav:
    - name: Blog
      url:  /

    - name: Curriculum Vitae
      url:  /curriculum-vitae/

    - name: Projects
      url: /projects/

css:
    - http://twitter.github.com/bootstrap/1.3.0/bootstrap.min.css
    - /css/my.css
    - /css/syntax.css
